### ISSUE TITLE
aumId

### ISSUE THREAD

**Issue by grzegorz914** [unknownskl/xbox-webapi-node#17]
Hi,

can we get current running aumId from Web Api, right now we get empty response from console status(focusAppAumid)?

**Comment by unknownskl** [comment]
I think there should be an api call which tells you what the current activity is, however I am not sure which call exactly. 

With the focusAumId I guess you are hinting on xbox-smartglass-core-node. For me this functionality still works on the stable xbox dashboard. Are you running the insiders dashboard?

**Comment by grzegorz914** [comment]
Yes I running insiders dashboard and all working as excepted but the focusAppAumid is empty, its from webApi response.


```
this.xbox.on('_on_console_status', (response, config, smartglass) => {...
response.packet_decoded.protected_payload.apps[0].aum_id
```
 In other thin in above code  we get the `aum_Id` for current running app, but not all app contain its `aum_Id` and sometimes the tile in HomeKit shows wrong current running input if aum_Id is null  or empty. I have checked this and all apps contain `oneStoreProductId` but this response is as a buffer which contain only null value. Any way to get current running `oneStoreProductId ` from console using `xbox-smartglass-core-node`.
