### ISSUE TITLE
which documentation do you use?

### ISSUE THREAD

**Issue by Vanish404** [unknownskl/xbox-webapi-node#19]
hey, thank you for building this great web api example. I wondering which documentation do you use to build this project? I just wanted to build my own project that will provide me list of games and prices for them. so could you help me, please?

**Comment by unknownskl** [comment]
Hey! The documentation used for this project can mostly be found on the microsoft website: https://docs.microsoft.com/en-us/gaming/xbox-live/api-ref/xbox-live-rest/uri/atoc-xboxlivews-reference-uris
