### ISSUE TITLE
implement authentication without user copy/pasting link

### ISSUE THREAD

**Issue by huertasdanny** [unknownskl/xbox-webapi-node#3]
I saw that you create the oauth link for signing into the xbox live account but it is possible to perform the request without copy pasting by having the username and password as part of the query string. Example can be found here: https://www.npmjs.com/package/async-xbox-live-api 

issue with their library is that it only works if running it as a node script. Their async-disk-cache package which they use for storing authentication credentials, does not work on web so I've been looking for alternatives.

**Comment by unknownskl** [comment]
I've been thinking about this and in favour of the possibility to use a native Oauth implementation i am going to close this issue. Entering xbox live credentials on 3rd party websites are not recommended and insecure.

The native oauth solution will be included in the v1 release, however the project aims to be used as a Nodejs script and not as a script that can be used in the browser.
